services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - bab-localstack-dev:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  opentofu:
    image: ghcr.io/opentofu/opentofu:latest
    volumes:
      - ./.opentofu/:/workspace
    working_dir: /workspace
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-localstack}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-localstack}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - TF_VAR_environment=${TF_VAR_environment:-development}
    depends_on:
      - localstack
    networks:
      - bab

  app-country:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    networks:
      - bab
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python manage.py health_check -s readiness && python manage.py health_check -s liveness",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bab-country-cdn:
  bab-localstack-dev:

networks:
  bab:
    driver: bridge