services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,lambda,apigateway,route53,rds
      - DEBUG=1
    volumes:
      - bab-localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - bab
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4566/health | grep '\"status\": \"running\"'"]
      interval: 10s
      timeout: 5s
      retries: 5

  opentofu:
    image: ghcr.io/opentofu/opentofu:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - TF_VAR_environment=local
    depends_on:
      - localstack
    networks:
      - bab

  app-country:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    networks:
      - bab
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python manage.py health_check -s readiness && python manage.py health_check -s liveness",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bab-country-cdn:
  bab-localstack:

networks:
  bab:
    driver: bridge